# Example of Docker Compose, a compose of container names, specify image and image name we used.
# If the image isn't in the docker hub, use build: ./ directory to app code and Dockerfile

# Specifying the version at the top of the file so that docker knows what version are you on
# The version 1 of docker compose cannot specify startup order, or specify network beside default bridge
# Version 3 introduce docker swarm

version: "3.4"

services:
  db:
    image: mysql:5.7
    command: >
      --max_allowed_packet=100M
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb_file_format=barracuda
      --innodb_file_per_table=On
      --innodb_large_prefix=On
    volumes:
      - ./db_data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: service
      MYSQL_PASSWORD: service
    ports:
      - "3306:3306"
    networks:
      - service_site
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    volumes: ["./wp/:/var/www/html"]
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
    networks:
      - service_site
  moodle:
    image: "moodlehq/moodle-php-apache:7.3"
    depends_on:
      - db
    volumes:
      - "./moodle/moodle_data:/var/www/html"
      - "./moodle/assets/web/apache2_faildumps.conf:/etc/apache2/conf-enabled/apache2_faildumps.conf"
    environment:
      MOODLE_DOCKER_DBTYPE: mysqli
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: root
      MOODLE_DOCKER_DBPASS: root
      MOODLE_DOCKER_DBCOLLATION: utf8mb4_unicode_ci
      MOODLE_DOCKER_PHP_VERSION: "7.3"
      MOODLE_DOCKER_WEB_PORT: 8001
      MOODLE_DOCKER_WEB_HOST: host.docker.internal
    ports:
      - "8001:80"
    networks:
      - service_site

networks:
  service_site:
volumes:
  db_data:
